# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainWindow.ui'
#
# Created: Wed Jan 21 16:40:23 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1176, 776)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(260, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stationTree = QtGui.QTreeWidget(self.layoutWidget)
        self.stationTree.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stationTree.sizePolicy().hasHeightForWidth())
        self.stationTree.setSizePolicy(sizePolicy)
        self.stationTree.setAutoFillBackground(False)
        self.stationTree.setStyleSheet("color: rgb(20, 20, 20);")
        self.stationTree.setDragDropOverwriteMode(False)
        self.stationTree.setAlternatingRowColors(True)
        self.stationTree.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.stationTree.setAnimated(True)
        self.stationTree.setObjectName("stationTree")
        self.stationTree.headerItem().setText(0, "1")
        self.stationTree.header().setVisible(False)
        self.verticalLayout.addWidget(self.stationTree)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(1, 22, 251, 29))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.compZbtn = QtGui.QPushButton(self.layoutWidget1)
        self.compZbtn.setCheckable(True)
        self.compZbtn.setChecked(True)
        self.compZbtn.setAutoExclusive(True)
        self.compZbtn.setObjectName("compZbtn")
        self.horizontalLayout_2.addWidget(self.compZbtn)
        self.compNbtn = QtGui.QPushButton(self.layoutWidget1)
        self.compNbtn.setCheckable(True)
        self.compNbtn.setAutoExclusive(True)
        self.compNbtn.setObjectName("compNbtn")
        self.horizontalLayout_2.addWidget(self.compNbtn)
        self.compEbtn = QtGui.QPushButton(self.layoutWidget1)
        self.compEbtn.setCheckable(True)
        self.compEbtn.setAutoExclusive(True)
        self.compEbtn.setObjectName("compEbtn")
        self.horizontalLayout_2.addWidget(self.compEbtn)
        self.verticalLayout.addWidget(self.groupBox)
        self.toolBox = QtGui.QToolBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(260, 390))
        self.toolBox.setFrameShape(QtGui.QFrame.HLine)
        self.toolBox.setFrameShadow(QtGui.QFrame.Raised)
        self.toolBox.setObjectName("toolBox")
        self.pageEvents = QtGui.QWidget()
        self.pageEvents.setGeometry(QtCore.QRect(0, 0, 258, 366))
        self.pageEvents.setObjectName("pageEvents")
        self.pickGroup = QtGui.QGroupBox(self.pageEvents)
        self.pickGroup.setGeometry(QtCore.QRect(0, 270, 256, 60))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pickGroup.sizePolicy().hasHeightForWidth())
        self.pickGroup.setSizePolicy(sizePolicy)
        self.pickGroup.setFlat(False)
        self.pickGroup.setCheckable(False)
        self.pickGroup.setObjectName("pickGroup")
        self.layoutWidget2 = QtGui.QWidget(self.pickGroup)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 25, 251, 29))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.pickP = QtGui.QPushButton(self.layoutWidget2)
        self.pickP.setStyleSheet("QPushButton#pickP:checked{background-color: green;};")
        self.pickP.setCheckable(True)
        self.pickP.setChecked(True)
        self.pickP.setAutoExclusive(True)
        self.pickP.setObjectName("pickP")
        self.gridLayout.addWidget(self.pickP, 0, 0, 1, 1)
        self.pickS = QtGui.QPushButton(self.layoutWidget2)
        self.pickS.setStyleSheet("QPushButton#pickS:checked{background-color: green;};")
        self.pickS.setCheckable(True)
        self.pickS.setAutoExclusive(True)
        self.pickS.setObjectName("pickS")
        self.gridLayout.addWidget(self.pickS, 0, 1, 1, 1)
        self.pickAmp = QtGui.QPushButton(self.layoutWidget2)
        self.pickAmp.setStyleSheet("QPushButton#pickAmp:checked{background-color: green;};")
        self.pickAmp.setCheckable(True)
        self.pickAmp.setAutoExclusive(True)
        self.pickAmp.setObjectName("pickAmp")
        self.gridLayout.addWidget(self.pickAmp, 0, 2, 1, 1)
        self.pick1 = QtGui.QPushButton(self.layoutWidget2)
        self.pick1.setStyleSheet("QPushButton#pick1:checked{background-color: green;};")
        self.pick1.setCheckable(True)
        self.pick1.setAutoExclusive(True)
        self.pick1.setObjectName("pick1")
        self.gridLayout.addWidget(self.pick1, 0, 3, 1, 1)
        self.pick2 = QtGui.QPushButton(self.layoutWidget2)
        self.pick2.setStyleSheet("QPushButton#pick2:checked{background-color: green;};")
        self.pick2.setCheckable(True)
        self.pick2.setAutoExclusive(True)
        self.pick2.setObjectName("pick2")
        self.gridLayout.addWidget(self.pick2, 0, 4, 1, 1)
        self.eventTree = QtGui.QTreeWidget(self.pageEvents)
        self.eventTree.setGeometry(QtCore.QRect(0, 0, 261, 231))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventTree.sizePolicy().hasHeightForWidth())
        self.eventTree.setSizePolicy(sizePolicy)
        self.eventTree.setMinimumSize(QtCore.QSize(260, 0))
        self.eventTree.setAlternatingRowColors(True)
        self.eventTree.setHeaderHidden(True)
        self.eventTree.setObjectName("eventTree")
        self.layoutWidget3 = QtGui.QWidget(self.pageEvents)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 240, 251, 29))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addEventBtn = QtGui.QPushButton(self.layoutWidget3)
        self.addEventBtn.setObjectName("addEventBtn")
        self.gridLayout_2.addWidget(self.addEventBtn, 0, 0, 1, 1)
        self.deleteItemBtn = QtGui.QPushButton(self.layoutWidget3)
        self.deleteItemBtn.setObjectName("deleteItemBtn")
        self.gridLayout_2.addWidget(self.deleteItemBtn, 0, 1, 1, 1)
        self.toolBox.addItem(self.pageEvents, "")
        self.pageFilter = QtGui.QWidget()
        self.pageFilter.setGeometry(QtCore.QRect(0, 0, 258, 366))
        self.pageFilter.setObjectName("pageFilter")
        self.labelFmax = QtGui.QLabel(self.pageFilter)
        self.labelFmax.setGeometry(QtCore.QRect(10, 32, 151, 25))
        self.labelFmax.setObjectName("labelFmax")
        self.filterButton = QtGui.QPushButton(self.pageFilter)
        self.filterButton.setGeometry(QtCore.QRect(10, 160, 241, 31))
        self.filterButton.setStyleSheet("border-color: rgb(154, 154, 154);\n"
"background-color: rgb(158, 234, 116);\n"
"alternate-background-color: rgb(255, 140, 140);")
        self.filterButton.setCheckable(True)
        self.filterButton.setAutoRepeat(True)
        self.filterButton.setFlat(False)
        self.filterButton.setObjectName("filterButton")
        self.labelFmin = QtGui.QLabel(self.pageFilter)
        self.labelFmin.setGeometry(QtCore.QRect(10, 0, 150, 25))
        self.labelFmin.setObjectName("labelFmin")
        self.fminSpin = QtGui.QDoubleSpinBox(self.pageFilter)
        self.fminSpin.setGeometry(QtCore.QRect(165, 0, 71, 26))
        self.fminSpin.setSuffix("")
        self.fminSpin.setMinimum(0.0)
        self.fminSpin.setMaximum(100.0)
        self.fminSpin.setSingleStep(1.0)
        self.fminSpin.setProperty("value", 1.0)
        self.fminSpin.setObjectName("fminSpin")
        self.fmaxSpin = QtGui.QDoubleSpinBox(self.pageFilter)
        self.fmaxSpin.setGeometry(QtCore.QRect(165, 30, 71, 26))
        self.fmaxSpin.setSuffix("")
        self.fmaxSpin.setMaximum(100.0)
        self.fmaxSpin.setProperty("value", 20.0)
        self.fmaxSpin.setObjectName("fmaxSpin")
        self.zerophaseCheck = QtGui.QCheckBox(self.pageFilter)
        self.zerophaseCheck.setGeometry(QtCore.QRect(130, 130, 97, 22))
        self.zerophaseCheck.setObjectName("zerophaseCheck")
        self.labelCorner = QtGui.QLabel(self.pageFilter)
        self.labelCorner.setGeometry(QtCore.QRect(10, 130, 66, 20))
        self.labelCorner.setObjectName("labelCorner")
        self.cornersSpin = QtGui.QSpinBox(self.pageFilter)
        self.cornersSpin.setGeometry(QtCore.QRect(70, 126, 40, 27))
        self.cornersSpin.setMinimum(2)
        self.cornersSpin.setMaximum(8)
        self.cornersSpin.setObjectName("cornersSpin")
        self.fminSlider = QtGui.QSlider(self.pageFilter)
        self.fminSlider.setEnabled(True)
        self.fminSlider.setGeometry(QtCore.QRect(10, 60, 221, 29))
        self.fminSlider.setMaximum(1000)
        self.fminSlider.setProperty("value", 10)
        self.fminSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fminSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.fminSlider.setTickInterval(100)
        self.fminSlider.setObjectName("fminSlider")
        self.fmaxSlider = QtGui.QSlider(self.pageFilter)
        self.fmaxSlider.setEnabled(True)
        self.fmaxSlider.setGeometry(QtCore.QRect(10, 90, 221, 29))
        self.fmaxSlider.setMaximum(1000)
        self.fmaxSlider.setProperty("value", 200)
        self.fmaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fmaxSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.fmaxSlider.setTickInterval(100)
        self.fmaxSlider.setObjectName("fmaxSlider")
        self.toolBox.addItem(self.pageFilter, "")
        self.qtGraphLayout = GraphicsLayoutWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qtGraphLayout.sizePolicy().hasHeightForWidth())
        self.qtGraphLayout.setSizePolicy(sizePolicy)
        self.qtGraphLayout.setObjectName("qtGraphLayout")
        self.horizontalLayout.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1176, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuInfo = QtGui.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Picks_as_CSV = QtGui.QAction(MainWindow)
        self.actionSave_Picks_as_CSV.setObjectName("actionSave_Picks_as_CSV")
        self.actionSave_Picks_for_Hypoinverse2000 = QtGui.QAction(MainWindow)
        self.actionSave_Picks_for_Hypoinverse2000.setObjectName("actionSave_Picks_for_Hypoinverse2000")
        self.actionLoad_JSON = QtGui.QAction(MainWindow)
        self.actionLoad_JSON.setObjectName("actionLoad_JSON")
        self.actionAs_JSON = QtGui.QAction(MainWindow)
        self.actionAs_JSON.setObjectName("actionAs_JSON")
        self.actionAs_CSV = QtGui.QAction(MainWindow)
        self.actionAs_CSV.setObjectName("actionAs_CSV")
        self.actionAs_HYP = QtGui.QAction(MainWindow)
        self.actionAs_HYP.setObjectName("actionAs_HYP")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit_2 = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit_2.setIcon(icon)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionExit_3 = QtGui.QAction(MainWindow)
        self.actionExit_3.setObjectName("actionExit_3")
        self.menuFile.addAction(self.actionAs_JSON)
        self.menuFile.addAction(self.actionLoad_JSON)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAs_CSV)
        self.menuFile.addAction(self.actionAs_HYP)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_3)
        self.menuInfo.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.labelCorner.setBuddy(self.cornersSpin)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.stationTree, self.qtGraphLayout)
        MainWindow.setTabOrder(self.qtGraphLayout, self.fminSpin)
        MainWindow.setTabOrder(self.fminSpin, self.fmaxSpin)
        MainWindow.setTabOrder(self.fmaxSpin, self.cornersSpin)
        MainWindow.setTabOrder(self.cornersSpin, self.zerophaseCheck)
        MainWindow.setTabOrder(self.zerophaseCheck, self.filterButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "GrapePicker", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Component View", None, QtGui.QApplication.UnicodeUTF8))
        self.compZbtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Shortcut Z Trace: 1", None, QtGui.QApplication.UnicodeUTF8))
        self.compZbtn.setStatusTip(QtGui.QApplication.translate("MainWindow", "Shortcut Z Trace: 1", None, QtGui.QApplication.UnicodeUTF8))
        self.compZbtn.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.compZbtn.setShortcut(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.compNbtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Shortcut N Trace: 2", None, QtGui.QApplication.UnicodeUTF8))
        self.compNbtn.setStatusTip(QtGui.QApplication.translate("MainWindow", "Shortcut N Trace: 2", None, QtGui.QApplication.UnicodeUTF8))
        self.compNbtn.setText(QtGui.QApplication.translate("MainWindow", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.compNbtn.setShortcut(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.compEbtn.setToolTip(QtGui.QApplication.translate("MainWindow", "Shortcut E Trace: 3", None, QtGui.QApplication.UnicodeUTF8))
        self.compEbtn.setStatusTip(QtGui.QApplication.translate("MainWindow", "Shortcut E Trace: 3", None, QtGui.QApplication.UnicodeUTF8))
        self.compEbtn.setText(QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.compEbtn.setShortcut(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.pickGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Active Picker", None, QtGui.QApplication.UnicodeUTF8))
        self.pickP.setToolTip(QtGui.QApplication.translate("MainWindow", "Shortcut P Pick: F1", None, QtGui.QApplication.UnicodeUTF8))
        self.pickP.setStatusTip(QtGui.QApplication.translate("MainWindow", "Shortcut P Pick: F1", None, QtGui.QApplication.UnicodeUTF8))
        self.pickP.setText(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.pickP.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.pickS.setToolTip(QtGui.QApplication.translate("MainWindow", "Shortcut S Pick: F2", None, QtGui.QApplication.UnicodeUTF8))
        self.pickS.setStatusTip(QtGui.QApplication.translate("MainWindow", "Shortcut S Pick: F2", None, QtGui.QApplication.UnicodeUTF8))
        self.pickS.setText(QtGui.QApplication.translate("MainWindow", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.pickS.setShortcut(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.pickAmp.setToolTip(QtGui.QApplication.translate("MainWindow", "Shortcut Amp Pick: F3", None, QtGui.QApplication.UnicodeUTF8))
        self.pickAmp.setStatusTip(QtGui.QApplication.translate("MainWindow", "Shortcut Amp Pick: F3", None, QtGui.QApplication.UnicodeUTF8))
        self.pickAmp.setText(QtGui.QApplication.translate("MainWindow", "Amp", None, QtGui.QApplication.UnicodeUTF8))
        self.pickAmp.setShortcut(QtGui.QApplication.translate("MainWindow", "F3", None, QtGui.QApplication.UnicodeUTF8))
        self.pick1.setToolTip(QtGui.QApplication.translate("MainWindow", "Shortcut 1 Pick: F5", None, QtGui.QApplication.UnicodeUTF8))
        self.pick1.setStatusTip(QtGui.QApplication.translate("MainWindow", "Shortcut 1 Pick: F5", None, QtGui.QApplication.UnicodeUTF8))
        self.pick1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.pick1.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.pick2.setToolTip(QtGui.QApplication.translate("MainWindow", "Shortcut 2 Pick: F6", None, QtGui.QApplication.UnicodeUTF8))
        self.pick2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Shortcut 2 Pick: F6", None, QtGui.QApplication.UnicodeUTF8))
        self.pick2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pick2.setShortcut(QtGui.QApplication.translate("MainWindow", "F6", None, QtGui.QApplication.UnicodeUTF8))
        self.eventTree.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.addEventBtn.setText(QtGui.QApplication.translate("MainWindow", "Add Event", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteItemBtn.setText(QtGui.QApplication.translate("MainWindow", "Delete Item", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageEvents), QtGui.QApplication.translate("MainWindow", "Event Picks", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFmax.setText(QtGui.QApplication.translate("MainWindow", "Upper Frequency Hz.", None, QtGui.QApplication.UnicodeUTF8))
        self.filterButton.setText(QtGui.QApplication.translate("MainWindow", "Filter On", None, QtGui.QApplication.UnicodeUTF8))
        self.filterButton.setShortcut(QtGui.QApplication.translate("MainWindow", "CapsLock", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFmin.setText(QtGui.QApplication.translate("MainWindow", "Lower Frequency Hz.", None, QtGui.QApplication.UnicodeUTF8))
        self.zerophaseCheck.setText(QtGui.QApplication.translate("MainWindow", "Zerophase", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCorner.setText(QtGui.QApplication.translate("MainWindow", "Corners", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageFilter), QtGui.QApplication.translate("MainWindow", "Bandpass Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInfo.setTitle(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Picks_as_CSV.setText(QtGui.QApplication.translate("MainWindow", "Save CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Picks_for_Hypoinverse2000.setText(QtGui.QApplication.translate("MainWindow", "Save Hypoinverse2000", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_JSON.setText(QtGui.QApplication.translate("MainWindow", "Open JSON", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_JSON.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAs_JSON.setText(QtGui.QApplication.translate("MainWindow", "Save JSON", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAs_JSON.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAs_CSV.setText(QtGui.QApplication.translate("MainWindow", "Export CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAs_HYP.setText(QtGui.QApplication.translate("MainWindow", "Export Hypoinverse2000", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_2.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_3.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit_3.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q, Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import GraphicsLayoutWidget
